/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalysisRequest {
  'principal' : Principal,
  'notes' : [] | [string],
  'strategyName' : string,
  'symbol' : string,
}
export interface AnalysisResult {
  'marketTrend' : string,
  'probability' : string,
  'stopLossSafety' : string,
  'takeProfit' : string,
  'explanation' : string,
  'stopLoss' : string,
  'timestamp' : Time,
  'entryPrice' : string,
  'signal' : string,
  'confidence' : string,
  'takeProfitProbability' : string,
  'riskLevel' : string,
  'strategyUsed' : string,
  'entryConfidence' : string,
}
export interface AnalysisWithImageRequest {
  'mimeType' : string,
  'imageBase64' : string,
  'notes' : [] | [string],
  'strategyName' : string,
  'symbol' : string,
}
export interface CommunityStrategy {
  'id' : string,
  'creator' : Principal,
  'votes' : bigint,
  'name' : string,
  'description' : string,
  'approved' : boolean,
  'timestamp' : Time,
  'strategyType' : string,
}
export interface CustomStrategy {
  'id' : string,
  'creator' : Principal,
  'name' : string,
  'description' : string,
  'timestamp' : Time,
  'howItWorks' : string,
}
export interface MarketPrice {
  'timestamp' : Time,
  'price' : string,
  'changePercent' : string,
  'symbol' : string,
}
export interface PriceAlert {
  'id' : string,
  'userId' : Principal,
  'targetPrice' : string,
  'timestamp' : Time,
  'triggered' : boolean,
  'symbol' : string,
  'condition' : string,
}
export interface SystemStatus {
  'geminiKeyCount' : bigint,
  'geminiModel' : string,
  'twelveDataKeyCount' : bigint,
}
export type Time = bigint;
export interface TradeEntry {
  'id' : string,
  'pnl' : string,
  'direction' : string,
  'strategy' : string,
  'notes' : string,
  'timestamp' : Time,
  'entryPrice' : string,
  'exitPrice' : string,
  'outcome' : string,
  'symbol' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGeminiKey' : ActorMethod<[string], undefined>,
  'addToWatchlist' : ActorMethod<[string], undefined>,
  'addTradeEntry' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    TradeEntry
  >,
  'approveStrategy' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAndTriggerAlerts' : ActorMethod<
    [Array<MarketPrice>],
    Array<PriceAlert>
  >,
  'clearAnalysisHistory' : ActorMethod<[], undefined>,
  'deleteCustomStrategy' : ActorMethod<[string], undefined>,
  'deleteStrategy' : ActorMethod<[string], undefined>,
  'deleteTradeEntry' : ActorMethod<[string], undefined>,
  'generateCustomStrategy' : ActorMethod<[string], CustomStrategy>,
  'getAnalysisHistory' : ActorMethod<[], Array<AnalysisResult>>,
  'getApprovedStrategies' : ActorMethod<[], Array<CommunityStrategy>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomStrategies' : ActorMethod<[], Array<CustomStrategy>>,
  'getFavoriteStrategies' : ActorMethod<[], Array<string>>,
  'getMarketPrices' : ActorMethod<[], Array<MarketPrice>>,
  'getPendingStrategies' : ActorMethod<[], Array<CommunityStrategy>>,
  'getPriceAlerts' : ActorMethod<[], Array<PriceAlert>>,
  'getSystemStatus' : ActorMethod<[], SystemStatus>,
  'getTradeEntries' : ActorMethod<[], Array<TradeEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWatchlist' : ActorMethod<[], Array<string>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectStrategy' : ActorMethod<[string], undefined>,
  'removeFromWatchlist' : ActorMethod<[string], undefined>,
  'removePriceAlert' : ActorMethod<[string], undefined>,
  'requestAIAnalysis' : ActorMethod<[AnalysisRequest], AnalysisResult>,
  'requestAIAnalysisWithImage' : ActorMethod<
    [AnalysisWithImageRequest],
    AnalysisResult
  >,
  'rotateGeminiKey' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAccessToken' : ActorMethod<[string, string], undefined>,
  'setPriceAlert' : ActorMethod<[string, string, string], PriceAlert>,
  'submitStrategy' : ActorMethod<[string, string, string], undefined>,
  'toggleFavoriteStrategy' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'voteOnStrategy' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];