/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const CustomStrategy = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'howItWorks' : IDL.Text,
});
export const AnalysisResult = IDL.Record({
  'marketTrend' : IDL.Text,
  'probability' : IDL.Text,
  'stopLossSafety' : IDL.Text,
  'takeProfit' : IDL.Text,
  'explanation' : IDL.Text,
  'stopLoss' : IDL.Text,
  'timestamp' : Time,
  'entryPrice' : IDL.Text,
  'signal' : IDL.Text,
  'confidence' : IDL.Text,
  'takeProfitProbability' : IDL.Text,
  'riskLevel' : IDL.Text,
  'strategyUsed' : IDL.Text,
  'entryConfidence' : IDL.Text,
});
export const CommunityStrategy = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'votes' : IDL.Int,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'approved' : IDL.Bool,
  'timestamp' : Time,
  'strategyType' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MarketPrice = IDL.Record({
  'timestamp' : Time,
  'price' : IDL.Text,
  'changePercent' : IDL.Text,
  'symbol' : IDL.Text,
});
export const AnalysisRequest = IDL.Record({
  'principal' : IDL.Principal,
  'notes' : IDL.Opt(IDL.Text),
  'strategyName' : IDL.Text,
  'symbol' : IDL.Text,
});
export const AnalysisWithImageRequest = IDL.Record({
  'mimeType' : IDL.Text,
  'imageBase64' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'strategyName' : IDL.Text,
  'symbol' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToWatchlist' : IDL.Func([IDL.Text], [], []),
  'approveStrategy' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAnalysisHistory' : IDL.Func([], [], []),
  'deleteCustomStrategy' : IDL.Func([IDL.Text], [], []),
  'deleteStrategy' : IDL.Func([IDL.Text], [], []),
  'generateCustomStrategy' : IDL.Func([IDL.Text], [CustomStrategy], []),
  'getAnalysisHistory' : IDL.Func([], [IDL.Vec(AnalysisResult)], ['query']),
  'getApprovedStrategies' : IDL.Func(
      [],
      [IDL.Vec(CommunityStrategy)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomStrategies' : IDL.Func([], [IDL.Vec(CustomStrategy)], ['query']),
  'getMarketPrices' : IDL.Func([], [IDL.Vec(MarketPrice)], []),
  'getPendingStrategies' : IDL.Func(
      [],
      [IDL.Vec(CommunityStrategy)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWatchlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectStrategy' : IDL.Func([IDL.Text], [], []),
  'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
  'requestAIAnalysis' : IDL.Func([AnalysisRequest], [AnalysisResult], []),
  'requestAIAnalysisWithImage' : IDL.Func(
      [AnalysisWithImageRequest],
      [AnalysisResult],
      [],
    ),
  'rotateGeminiKey' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAccessToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitStrategy' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'voteOnStrategy' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const CustomStrategy = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'howItWorks' : IDL.Text,
  });
  const AnalysisResult = IDL.Record({
    'marketTrend' : IDL.Text,
    'probability' : IDL.Text,
    'stopLossSafety' : IDL.Text,
    'takeProfit' : IDL.Text,
    'explanation' : IDL.Text,
    'stopLoss' : IDL.Text,
    'timestamp' : Time,
    'entryPrice' : IDL.Text,
    'signal' : IDL.Text,
    'confidence' : IDL.Text,
    'takeProfitProbability' : IDL.Text,
    'riskLevel' : IDL.Text,
    'strategyUsed' : IDL.Text,
    'entryConfidence' : IDL.Text,
  });
  const CommunityStrategy = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'votes' : IDL.Int,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'approved' : IDL.Bool,
    'timestamp' : Time,
    'strategyType' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MarketPrice = IDL.Record({
    'timestamp' : Time,
    'price' : IDL.Text,
    'changePercent' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const AnalysisRequest = IDL.Record({
    'principal' : IDL.Principal,
    'notes' : IDL.Opt(IDL.Text),
    'strategyName' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const AnalysisWithImageRequest = IDL.Record({
    'mimeType' : IDL.Text,
    'imageBase64' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'strategyName' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToWatchlist' : IDL.Func([IDL.Text], [], []),
    'approveStrategy' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAnalysisHistory' : IDL.Func([], [], []),
    'deleteCustomStrategy' : IDL.Func([IDL.Text], [], []),
    'deleteStrategy' : IDL.Func([IDL.Text], [], []),
    'generateCustomStrategy' : IDL.Func([IDL.Text], [CustomStrategy], []),
    'getAnalysisHistory' : IDL.Func([], [IDL.Vec(AnalysisResult)], ['query']),
    'getApprovedStrategies' : IDL.Func(
        [],
        [IDL.Vec(CommunityStrategy)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomStrategies' : IDL.Func([], [IDL.Vec(CustomStrategy)], ['query']),
    'getMarketPrices' : IDL.Func([], [IDL.Vec(MarketPrice)], []),
    'getPendingStrategies' : IDL.Func(
        [],
        [IDL.Vec(CommunityStrategy)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWatchlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectStrategy' : IDL.Func([IDL.Text], [], []),
    'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
    'requestAIAnalysis' : IDL.Func([AnalysisRequest], [AnalysisResult], []),
    'requestAIAnalysisWithImage' : IDL.Func(
        [AnalysisWithImageRequest],
        [AnalysisResult],
        [],
      ),
    'rotateGeminiKey' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAccessToken' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitStrategy' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'voteOnStrategy' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };